balkancottage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('balkancottageapp.urls'), name='balkancottageapp_urls'),
    path('accounts/', include('allauth.urls'))
]

balkancottageapp/urls.py
from . import views
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import CreateReservation, MyReservations, Menu, UpdateReservation

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('menu', views.MenuList.as_view(), name='menu'),
    path('reservation/', views.CreateReservation.as_view(), name='reservation'),
    path('my_reservations/', views.MyReservations.as_view(), name='my_reservations'),
    path('update_reservation/<int:pk>/update/', views.UpdateReservation.as_view(), name='update_reservation'),
    path('delete/<reservation_id>', views.delete_reservation, name='delete'),

]

balkancottageapp/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField



STATUS = ((0, "Draft"), (1, "Published"))


class Home(models.Model):

    welcome_page = models.CharField(max_length=120)


# Model for the Menu which is created by the Admin
class Menu(models.Model):
    dish_name = models.CharField(max_length=130)
    image = CloudinaryField('image', default='')
    content = models.CharField(max_length=200)
    status = models.IntegerField(choices=STATUS, default=0)



# Reservation model

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reservation_date = models.DateField()
    reservation_time = models.TimeField()
    message = models.TextField(default='Special requests, alergies etc.', max_length=300)

balkancottageapp/forms.py
from django import forms
from .models import Reservation
from datetime import datetime, timedelta



class ReservationTableForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['reservation_date', 'reservation_time', 'message']
        widgets = {
            'reservation_date': forms.DateInput(attrs={'type': 'date'}),
            'reservation_time': forms.TimeInput(attrs={'type': 'time'})
        }
        message = forms.TextInput()

balkancottageapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic, View
from django.views.generic.edit import UpdateView, DeleteView
from .models import Menu, Home, Reservation
from .forms import ReservationTableForm
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.forms import Form
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib import messages


class HomePage(generic.ListView):
    model = Home
    template_name = 'index.html'


class MenuList(generic.ListView):
    model = Menu
    # decide by which order to sort later
    queryset = Menu.objects.filter(status=1)
    template_name = 'menu.html'
    paginate_by = 6


class CreateReservation(LoginRequiredMixin, View):
    model = Reservation
    template_name = 'reservation.html'

    def get(self, request):
        form = ReservationTableForm
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        if request.method == 'POST':
            form = ReservationTableForm(request.POST)
            if form.is_valid():
                reservation_date = form.cleaned_data['reservation_date']
                reservation_time = form.cleaned_data['reservation_time']
                message = form.cleaned_data['message']
                success_msg = self.validate_reservation(request.user, reservation_date, reservation_time)
                if success_msg:
                    reservation = Reservation(user=request.user, reservation_date=reservation_date, reservation_time=reservation_time, message=message)
                    reservation.save()
                    user_reservations = Reservation.objects.filter(user=request.user)
                    return render(request, 'my_reservations.html', {'user_reservations': user_reservations})
                else:
                    return render(request, 'reservation.html', {'form': form})
        else:
            form = ReservationTableForm()
        return render(request, 'reservation.html', {'form': form})
            
    def validate_reservation(self, user, reservation_date, reservation_time):
        """
        This functions validates the reservation by checking the existence
        of another reservation indicating potential overlapping and avoiding
        conflicts if there is a reservation in a certain time period.
        """

        if reservation_date.weekday() == 6:
            messages.error(self.request, 'Sorry, We are closed on Sundays')
            return None

        existing_reservation = Reservation.objects.filter(
            reservation_date=reservation_date,
            reservation_time=reservation_time,
            user=self.request.user
        )
        if existing_reservation.exists():
            messages.error(self.request, 'Ups, there is already a reservation in the selected period')
            return None
        else:
            return True, None


class MyReservations(ListView, LoginRequiredMixin):
    model = Reservation
    template_name = 'my_reservations.html'

    def get_queryset(self):
        return Reservation.objects.filter(user=self.request.user)


class UpdateReservation(LoginRequiredMixin, UpdateView):
    model = Reservation
    form_class = ReservationTableForm
    template_name = 'my_reservations.html'

    def get_success_url(self):
        return reverse_lazy('my_reservations')

    def form_valid(self, form):

        reservation_date = form.cleaned_data['reservation_date']
        reservation_time = form.cleaned_data['reservation_time']
        check_overlap = self.check_double_reservation(self.request, reservation_date, reservation_time)
        if not check_overlap:
            return self.form_invalid(form)
        return super().form_valid(form)

    def check_double_reservation(self, request, reservation_date, reservation_time):
        existing_reservation = Reservation.objects.filter(
            reservation_date=reservation_date,
            reservation_time=reservation_time,
            user=self.request.user
        ).exclude(pk=self.kwargs['pk'])
        if reservation_date.weekday() == 6:
            messages.error(self.request, 'Sorry, We are closed on Sundays')
            return None

        if existing_reservation.exists():
            messages.error(self.request, 'Ups, there is already a reservation in the selected period')
            return False
        else:
            return True, None
        
        
def delete_reservation(request, reservation_id):
    reservation_to_delete = get_object_or_404(Reservation, id=reservation_id)
    reservation_to_delete.delete()
    return redirect('my_reservations')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <title>Balkan Cottage</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Cormorant:wght@600&family=Crete+Round&display=swap"
        rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/87e547263b.js" crossorigin="anonymous"></script>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body class="d-flex flex-column h-100">
    <!--Navigation-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="{% url 'home' %}">Balkan Cottage</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active text-white" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'reservation' %}">Reservations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'menu' %}">Menu</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'my_reservations' %}">My Reservations</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'account_login' %}">Sign In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    <!--Content-->

    {% endblock content %}
    <!--Footer-->

    <footer class="footer py-3 bg-light mt-auto">
        <div class="container">
            <div class="row flex-column flex-md-row justify-content-center">
                <div class="col-md-4 mb-3 mb-md-0">
                    <h4>Opening hours</h4>
                    <ul class="list-unstyled text-small text-white">
                        <li>Monday-Saturday</li>
                        <br />
                        <li>12h-00h</li>
                        <br />
                        <li>Sunday</li>
                        <br />
                        <li>CLOSED</li>
                        <br />
                    </ul>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <h4>Contact Us</h4>
                    <ul class="list-unstyled text-small text-white">
                        <li>Oak Road 357</li>
                        <br />
                        <li>Lopusnik, Serbia</li>
                        <br />
                        <li>Phone: +381 55 66 85 455</li>
                        <br />
                        <li>Email: balkancottage@balkancottage.com</li>
                        <br />
                    </ul>
                </div>
                <!--This part of code is copied from django blog project made by code institute-->
                <div class="col-md-4 mb-3 mb-md-0">
                    <p class="m-0 text-center text-white">
                        Made by Stefan Stanisavljevic
                    </p>
                    <p class="m-0 text-center text-white">
                        Follow us:
                        <i class="fab fa-facebook-square ms-3"></i>
                        <i class="fab fa-instagram-square ms-3"></i>
                    </p>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<img src="https://res.cloudinary.com/dsqztoyqt/image/upload/v1690826304/homebackground_macasl.jpg" alt="fire grill" id="bg-cover">

{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="row" style="width: 25rem;">
    {% for menu in menu_list %}
    <div class="col-md-6 mb-4">
      <div class="card h-100">
    <img src="{{ menu.image.url }}" class="card-img-top img-fluid" alt="piece of meat grilled">
    <div class="card-body"> 
      <h5 class="card-title">{{ menu.dish_name }}</h5>
      <p>{{ menu.content | safe }}</p>
    </div>
    </div>
  </div>
    {% endfor %}

  </div>  

  
{% endblock %} 

            
                

templates/my_reservations.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% load crispy_forms_tags %}
<section>
    <div class="container">
        {% if user.is_authenticated %}
        {% for reservation in object_list %}
        {% if request.user == reservation.user %}
        <h2>My Reservation:</h2>
        <ul>


            <li>
                Date: {{ reservation.reservation_date }} | Time: {{ reservation.reservation_time }} | Message: {{ reservation.message }}
                <a href="{% url 'update_reservation' pk=reservation.pk %}">Update your reservation</a><br>
                <a href="/delete/{{ reservation.id}}">Cancel your reservation</a>
            </li>

            {% endif %}
        </ul>
        {% endfor %}

        {% endif %}
    </div>

    {% if request.resolver_match.url_name == 'update_reservation' %}
    <div class="container">
        <h2>Update reservation</h2>

        <p>{{ user.username }}</p>
        <form method="POST">
            {% csrf_token %}
            {{ form | crispy }}

            <div>
                
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li> {% if message.tags %} {{ message }} {% endif %}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <button type="submit">Update your existing reservation</button>
        </form>

        {% endif %}
    </div>
</section>



{% endblock %} 

templates/reservation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% load crispy_forms_tags %}

<section>
    <div class="container">

        {% if user.is_authenticated %}
        <h2>Make a reservation</h2>

        <p>{{ user.username }}</p>
        <form method="POST">
            {% csrf_token %}
            {{ form | crispy }}

          
            <div>
                
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li> {% if message.tags %} {{ message }} {% endif %}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
          


            <button type="submit">Submit</button>
        </form>
        {% else %}
        <p>Please login at </p>
        {% endif %}
    </div>
</section>



{% endblock %} 